## Serverless config
## https://serverless.com/framework/docs

## Name for overall service (collection of functions)
service: canteenbot

## AWS details
provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  profile: elliot
  stage: prod

  ## Service-wide environment variables
  environment:
    # CORE_URL: https://8049upo37k.execute-api.eu-west-1.amazonaws.com/dev/core
    CORE_URL: https://3wt5txpgb1.execute-api.eu-west-1.amazonaws.com/prod/core

## Individual parts of the service
functions:
  ## CanteenBot's core
  core:
    handler: dist/core.handler
    events:
      - http:
          path: /core
          method: get
    environment:
      DATA_URL: http://elliotdavies.co.uk/dev/menu/

  ## Slash-command listener
  slack:
    handler: dist/slack.handler
    events:
      - http:
          path: /slack
          method: post
    environment:
      TIMES_TEAM: TqKr8LRrC7yP9eHiC54dznHS
      # TIMES_TEAM: uK8HKof9vicacg1yD5hiKori

  ## Post to Slack on a schedule
  slack-notifier:
    handler: dist/slack-notifier.handler
    events:
      - schedule: cron(15 12 * * ? *)
    environment:
      WEBHOOK_URL: https://hooks.slack.com/services/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

## Bundling options
package:
  # individually: true
  exclude:
    - node_modules/**
    - assets/**
    - data/**
    - package.json
    - .gitignore
    - README.md
  # include:
  #   lib/**


## Examples of event types
# events:
#   - http:
#     path: users/create
#     method: get
#   - s3: ${env:BUCKET}
#   - schedule: rate(10 minutes)
#   - sns: greeter-topic
#   - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#   - alexaSkill
#   - iot:
#     sql: "SELECT * FROM 'some_topic'"

## Examples of adding CloudFormation resource templates
# resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
